site_name: Learn Git
site_url: https://digital-initiatives-kangan-institute.github.io/learn-git/
nav:
  - Home:
    - Introduction: index.md
  - Course:
    - Installing Git: pages/course/install-git.md
    - Branching Strategy: pages/course/branching-strategy.md
    - Pull Requests: pages/course/pull-requests.md
  - Quick Info:
    - Git Cheatsheet: pages/quick-info/cheat-sheet.md
    - Live Preview: pages/quick-info/live-preview-extension.md
  - Activities: 
    - Activity 1 - Edit, Commit, Repeat: pages/activities/activity-1.md
  - Debug:
    - Custom Controls: pages/debug/custom-controls.md
theme: readthedocs
hooks:
  - hooks/note.py
  - hooks/button.py
  - hooks/quiz.py
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascript/main.js
  - javascript/quiz.js
