site_name: Learn Git
nav:
  - Home:
    - Introduction: index.md
  - Course:
    - Installing Git: pages/course/install-git.md
    - Branching Strategy: pages/course/branching-strategy.md
  - Quick Info:
    - Git Cheatsheet: pages/quick-info/cheat-sheet.md
  - Activities: 
    - Activity 1 - Edit, Commit, Repeat: pages/activities/activity-1.md
theme: readthedocs
hooks:
  - hooks/note.py
  - hooks/button.py
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascript/main.js
